all:
  children:
    sportspuff_servers:
      hosts:
        host77.nird.club:
          ansible_user: "{{ lookup('env', 'SPORTSPUFF_USER') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'SPORTSPUFF_SSH_KEY') }}"
          ansible_python_interpreter: /usr/bin/python3
        host78.nird.club:
          ansible_user: "{{ lookup('env', 'SPORTSPUFF_USER') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'SPORTSPUFF_SSH_KEY') }}"
          ansible_python_interpreter: /usr/bin/python3
      vars:
        # Common variables for all sportspuff servers
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no' 